### ISSUE TITLE
在approve list里面，增加三个字段，具体如下

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#100]
![image](https://cloud.githubusercontent.com/assets/17737516/18462994/581c4ddc-79b9-11e6-83cd-b19c4cf4becc.png)

具体的值，就是工单里面的对应的值

**Comment by Ge-Fei** [comment]
已加：
![image](https://cloud.githubusercontent.com/assets/15045906/18473227/5d8c661e-79ee-11e6-8850-6cd7aea02834.png)
