### ISSUE TITLE
外网的attachment的按钮，点击的时候没有反应

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#101]
![image](https://cloud.githubusercontent.com/assets/17737516/18464582/6edeb928-79c4-11e6-8a2b-61c9e7f60849.png)

**Comment by richardzhai01** [comment]
你用这个账号去重现吧
milla.lu@ericsson.com

**Comment by Ge-Fei** [comment]
没重现出来，本地这边改成了点击attachment的不连接ftp，只有点击load时候才加载文件列表

**Comment by Ge-Fei** [comment]
已重现并解决。
