### ISSUE TITLE
外网的页面的字段值的改变，comments -> Result Desc

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#102]
![image](https://cloud.githubusercontent.com/assets/17737516/18468179/5a729e08-79d5-11e6-9ed3-493a4df71297.png)

**Comment by Ge-Fei** [comment]
你是哪个工单，我看到腾讯云上面是Result Desc:
![image](https://cloud.githubusercontent.com/assets/15045906/18473476/ba0a171e-79ef-11e6-8e47-ee897e1b673b.png)

**Comment by richardzhai01** [comment]
在创建的页面，点击create的时候
