### ISSUE TITLE
当update工单的时候，要验证是否当前的处理人打开工单操作

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#103]
当在NCM WO打开工单操作时，要验证是否当前状态的email地址操作工单，如果是当前的人操作，就可以显示send，edit，save，OPI Select, Get OPI, Fetch OPI的按钮

如果不是当前的人，send，edit，save, OPI Select, Get OPI, Fetch OPI的按钮不能显示
![image](https://cloud.githubusercontent.com/assets/17737516/18469360/806cbe68-79da-11e6-8a46-258664bfbabe.png)

![image](https://cloud.githubusercontent.com/assets/17737516/18469458/d549facc-79da-11e6-818a-a6c37a431c06.png)

**Comment by Ge-Fei** [comment]
怎么处理？怎么判断打开update的时候是否是当前人处理？视乎有待商讨？

**Comment by Ge-Fei** [comment]
已处理，并且更新到腾讯云
