### ISSUE TITLE
当WO approve后，owner的字段是高亮的

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#105]
![image](https://cloud.githubusercontent.com/assets/17737516/18499145/d319bcbc-7a6e-11e6-883c-a1b53d024ce1.png)

**Comment by Ge-Fei** [comment]
![image](https://cloud.githubusercontent.com/assets/15045906/18502892/9720d5ce-7a8c-11e6-8327-4fe36c92824e.png)
已处理
