### ISSUE TITLE
Approve的页面的调整，尽量不要有滚动条，还有actual start和end time是取整

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#108]
![image](https://cloud.githubusercontent.com/assets/17737516/18501870/00198a1e-7a86-11e6-8e99-bc684bf2b150.png)

**Comment by Ge-Fei** [comment]
![image](https://cloud.githubusercontent.com/assets/15045906/18502708/347da5ce-7a8b-11e6-85de-8f583f55c02f.png)
