### ISSUE TITLE
New OPI的时候， Number of Reference， Document Responsible， Sort by的值显示问题

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#109]
![image](https://cloud.githubusercontent.com/assets/17737516/18612641/ff02ff0c-7d91-11e6-83b4-2b9bf05395ff.png)

![image](https://cloud.githubusercontent.com/assets/17737516/18612656/4d151ce8-7d92-11e6-84fa-af018486d594.png)

![image](https://cloud.githubusercontent.com/assets/17737516/18612674/9fa46be4-7d92-11e6-92cb-7fec753f3548.png)

**Comment by linkcmkaizhang** [comment]
已修正，下班后更新到腾讯云
