### ISSUE TITLE
在OPI的update中，去掉history version的attachment的操作

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#110]
![image](https://cloud.githubusercontent.com/assets/17737516/18612713/db1474a2-7d93-11e6-8352-2bacf8990585.png)

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18614778/25db227c-7dc8-11e6-85ac-f6d8f944a171.png)
