### ISSUE TITLE
当点击forwards to，suspend等按钮之后的时候，下一个人看不到选择的OPI， 当前的人也看不到， 而且在OPI的搜索的时候也查找不到

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#111]
当前的状态
![image](https://cloud.githubusercontent.com/assets/17737516/18612766/46dfe594-7d95-11e6-8ee5-cbaad5cfd5fd.png)

张凯的账号查看的：
![image](https://cloud.githubusercontent.com/assets/17737516/18612772/5f8a4e40-7d95-11e6-9127-6319489302c2.png)

用richard zhai的账号查看的
![image](https://cloud.githubusercontent.com/assets/17737516/18612775/816941c4-7d95-11e6-881a-f19d7e66f7dd.png)

点击suspend，再点continue的时候
![image](https://cloud.githubusercontent.com/assets/17737516/18612793/68195186-7d96-11e6-9759-7667383eecbc.png)

当OPI search的时候，当前创建的OPI的查找不到
![image](https://cloud.githubusercontent.com/assets/17737516/18612814/397631f4-7d97-11e6-87e3-ad4ad76eaabf.png)

**Comment by chulingchen** [comment]
forward to的时候：由chuling forward to zhangkai
![image](https://cloud.githubusercontent.com/assets/17737744/18613558/ffdd2ad8-7daf-11e6-9a9c-a96e9e250737.png)
chuling查看：
![image](https://cloud.githubusercontent.com/assets/17737744/18613570/1ceb38c2-7db0-11e6-9992-6439ad36ab16.png)

zhangkai查看：
![image](https://cloud.githubusercontent.com/assets/17737744/18613554/ecdc4ef0-7daf-11e6-850c-63addc426c31.png)

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18613709/9bd04a5e-7db2-11e6-887c-6505d6ecffc3.png)
![image](https://cloud.githubusercontent.com/assets/17737744/18613713/a68f5444-7db2-11e6-9cbe-64af6590119e.png)
suspended的时候打开：
![image](https://cloud.githubusercontent.com/assets/17737744/18613718/bea94be8-7db2-11e6-880a-73a9ba68afb7.png)
点击contcontinue后：
![image](https://cloud.githubusercontent.com/assets/17737744/18613723/dc79864c-7db2-11e6-8976-3db4a2bdf5ed.png)
OPI search：
![image](https://cloud.githubusercontent.com/assets/17737744/18613733/161e959a-7db3-11e6-85da-9fa8b355930e.png)
