### ISSUE TITLE
通过NCM WO处理工单的时候，跳步的处理，在handle list出现有两条的记录

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#115]
过程如下：
1. 创建工单，只是填task confirm为自己，选择一份opi，然后点击send
2. 在handle list有一个记录：
![image](https://cloud.githubusercontent.com/assets/17737516/18613098/82178838-7da4-11e6-883d-bc2495c81b48.png)
1. 通过NCM WO处理工单
   ![image](https://cloud.githubusercontent.com/assets/17737516/18613103/9daebaf8-7da4-11e6-9101-1d006c4094b5.png)
2. 填满全部的人名
   ![image](https://cloud.githubusercontent.com/assets/17737516/18613108/c6b36b24-7da4-11e6-8774-b34f898e343b.png)
3. 在handle list有两条的记录
   ![image](https://cloud.githubusercontent.com/assets/17737516/18613111/eecf87dc-7da4-11e6-99b5-2969ab4df118.png)

**Comment by linkcmkaizhang** [comment]
已解决，下班后更新腾讯云
