### ISSUE TITLE
流程到了expert的时候，不能高亮

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#116]
1. 在handle list里面已经到了expert的状态了
   ![image](https://cloud.githubusercontent.com/assets/17737516/18613137/a9585f34-7da5-11e6-963d-d1fb24ac39c8.png)
2. 但是在NCM WO里面不能高亮
   ![image](https://cloud.githubusercontent.com/assets/17737516/18613143/cb7e40d8-7da5-11e6-83d7-4169a5f68c1f.png)

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18613386/5f45c60a-7dac-11e6-9124-9998a4a0f836.png)
![image](https://cloud.githubusercontent.com/assets/17737744/18613389/6a631baa-7dac-11e6-91e6-f2b1b9070848.png)
