### ISSUE TITLE
在approve的页面，点击OPI resource的时候，出现system error

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#118]
![image](https://cloud.githubusercontent.com/assets/17737516/18613821/bcdd7dbe-7db4-11e6-98b9-d486e9b8505d.png)

![image](https://cloud.githubusercontent.com/assets/17737516/18613822/c15e66d2-7db4-11e6-9fd5-fa5d07e60330.png)

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18614495/0497af64-7dc2-11e6-8512-e20b7b06aee5.png)
