### ISSUE TITLE
找回密码的功能

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#12]
找回密码
![image](https://cloud.githubusercontent.com/assets/17737516/17884968/a20342ba-694d-11e6-8df8-39902307f7ea.png)

**Comment by Ge-Fei** [comment]
![image](https://cloud.githubusercontent.com/assets/15045906/17926924/fb6dcf18-6a25-11e6-8c9c-045d34a5ec33.png)
![image](https://cloud.githubusercontent.com/assets/15045906/17926945/0d2c595e-6a26-11e6-8b85-8f1e59b3f99f.png)
请查看上面的功能图片

**Comment by Ge-Fei** [comment]
![image](https://cloud.githubusercontent.com/assets/15045906/17926966/29b8a50a-6a26-11e6-8df0-8e99a0441c42.png)

**Comment by richardzhai01** [comment]
把文字提示信息表述清楚点，像Forgot password successfully..., 要改成 Please check your email for your password.

还有， 
![image](https://cloud.githubusercontent.com/assets/17737516/17954224/02f34368-6aac-11e6-8dae-b31036c877e6.png)

上面的Login和forgot password都显示不清楚的
