### ISSUE TITLE
当owner上传附件的时候，在handle list里面是显示NCM Result

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#120]
![image](https://cloud.githubusercontent.com/assets/17737516/18613918/b985cb2e-7db6-11e6-9551-b48aca9d8399.png)

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18614228/83e2cfa6-7dbd-11e6-9e46-d1d8445a8612.png)
