### ISSUE TITLE
当工单approve之后，通过handle list进去工单，approver不能改的

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#121]
1. 通过handle list进去处理工单
   ![image](https://cloud.githubusercontent.com/assets/17737516/18613941/36b0fb6e-7db7-11e6-989f-77d7eec4c322.png)
2. approver的位置
   ![image](https://cloud.githubusercontent.com/assets/17737516/18613951/5a01fe2e-7db7-11e6-9779-165d59813c7b.png)

**Comment by linkcmkaizhang** [comment]
已修正，下班后更新腾讯云
