### ISSUE TITLE
在上传result log的时候，在save的时候，就要验证是否有result log的存在

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#122]
现在的情况是，点击save的时候，如果没有附件，有以下的提示
![image](https://cloud.githubusercontent.com/assets/17737516/18613991/f731d4d0-7db7-11e6-95bc-224a67aa10ba.png)

正确的做法是在save的时候，就要验证有无log的上传，没有，要上传才可以save，如果有，就save，然后提示是否发送

**Comment by chulingchen** [comment]
save时：
![image](https://cloud.githubusercontent.com/assets/17737744/18614359/8f35a67e-7dbf-11e6-85f8-bb03babb0e8c.png)

**Comment by richardzhai01** [comment]
提示信息改成：
Please click the "Result Log" button to upload the log first.

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18614832/3698a962-7dc9-11e6-87a3-cf1f81b3d1bc.png)
