### ISSUE TITLE
在Close WO的时候，从NCM WO进入，在update的页面加上Close WO的按钮，跳转到Close WO的页面

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#124]
![image](https://cloud.githubusercontent.com/assets/17737516/18614393/640b3d1e-7dc0-11e6-951b-68e0c8d93316.png)

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18614764/ce663c02-7dc7-11e6-98d7-891b4b1f9ca5.png)
![image](https://cloud.githubusercontent.com/assets/17737744/18614765/d4d20cec-7dc7-11e6-8004-f27d10e9b1c7.png)
