### ISSUE TITLE
在创建工单的页面中， coments还没有改成Result Desc

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#125]
![image](https://cloud.githubusercontent.com/assets/17737516/18614438/597311dc-7dc1-11e6-9552-f9fe66d21c55.png)

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18614518/6ebc5caa-7dc2-11e6-91bd-3e01cd7d4710.png)
