### ISSUE TITLE
选择现有的OPI的时候，NE Type没有把值带出来

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#126]
![image](https://cloud.githubusercontent.com/assets/17737516/18614547/e7ff0f04-7dc2-11e6-92b1-838eb1c5774c.png)

其他值也没有带出来
![image](https://cloud.githubusercontent.com/assets/17737516/18614758/a4b2bad4-7dc7-11e6-8da2-823ee3acdd4f.png)

**Comment by linkcmkaizhang** [comment]
更新到腾讯云了
