### ISSUE TITLE
Change Password

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#13]
![image](https://cloud.githubusercontent.com/assets/17737516/17885099/433b529e-694e-11e6-8c48-2e3a59e0be54.png)

**Comment by Ge-Fei** [comment]
![image](https://cloud.githubusercontent.com/assets/15045906/17927040/746dedb2-6a26-11e6-94ab-1ddb064d0396.png)
![image](https://cloud.githubusercontent.com/assets/15045906/17927052/848c79a2-6a26-11e6-88a4-e0f05f30fd5f.png)
![image](https://cloud.githubusercontent.com/assets/15045906/17927060/91c0aef4-6a26-11e6-8ee1-9deb8353711f.png)
![image](https://cloud.githubusercontent.com/assets/15045906/17927088/ab253d92-6a26-11e6-9121-5fbcb0aef082.png)
![image](https://cloud.githubusercontent.com/assets/15045906/17927103/bd63b6b4-6a26-11e6-9620-2a74c08e7c83.png)

**Comment by richardzhai01** [comment]
![image](https://cloud.githubusercontent.com/assets/17737516/17954250/2b433f6c-6aac-11e6-904e-239bf194c778.png)
大小写要注意， Update Password

还有
![image](https://cloud.githubusercontent.com/assets/17737516/17954270/5067c088-6aac-11e6-9a84-0c5dc65bc0c4.png)

不太明显吧，你不说，我都不知道是change password
