### ISSUE TITLE
点击update的时候， OPI选择的按钮看不到

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#19]
![image](https://cloud.githubusercontent.com/assets/17737516/18073710/92132d0a-6e9a-11e6-8cc3-a44981e5b977.png)

当update的时候，OPI的选择的按钮没有看到

**Comment by Ge-Fei** [comment]
是否有把最新的证书和数据放到C盘下面？

**Comment by richardzhai01** [comment]
![image](https://cloud.githubusercontent.com/assets/17737516/18074661/cdb5c45c-6ea0-11e6-88bf-72e0a72e8ec8.png)

下载证书之后，重新打开ie，还是这种情况

**Comment by Ge-Fei** [comment]
已经ok了，请在试试
