### ISSUE TITLE
按钮的位置的调整，调整成图标的样子

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#20]
![image](https://cloud.githubusercontent.com/assets/17737516/18073803/29fc35da-6e9b-11e6-9a53-cb0707d14d49.png)

调整的顺序：
Update，Forwards To， Cancel， Suspend， Log File 改成attachment， ShowMonitor, Result Log, 这些都换成图标，其他的就不要显示了

**Comment by richardzhai01** [comment]
图标的样式，可以参考update页面里面的
![image](https://cloud.githubusercontent.com/assets/17737516/18074169/657ac746-6e9d-11e6-8cd1-bc24d3843e02.png)

![image](https://cloud.githubusercontent.com/assets/17737516/18074195/952c4e56-6e9d-11e6-972e-59c6ec65e9c5.png)

**Comment by chulingchen** [comment]
forward to 按钮之前是没有在列表中的，是否需要加上
![image](https://cloud.githubusercontent.com/assets/17737744/18082500/d3988644-6ed1-11e6-8651-f08ae229f843.png)

**Comment by richardzhai01** [comment]
可以啊，图标这样就ok啦，forwards to加上吧

**Comment by chulingchen** [comment]
forwards to已经加上
![image](https://cloud.githubusercontent.com/assets/17737744/18113438/6e83a90a-6f62-11e6-9b02-723bb80e3e7b.png)
