### ISSUE TITLE
Update的页面不可以编辑的

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#21]
![image](https://cloud.githubusercontent.com/assets/17737516/18074023/33ace7a4-6e9c-11e6-867a-a9442a29352f.png)

点击后的页面
![image](https://cloud.githubusercontent.com/assets/17737516/18074041/494adf62-6e9c-11e6-8c8c-363f6372e278.png)

**Comment by chulingchen** [comment]
这个问题是由于js中读取文件的那个地方出错了导致下面的js没有加载到引起的，已调整了代码位置解决
