### ISSUE TITLE
页面的搜索条件增加，增加NCM no

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#22]
![image](https://cloud.githubusercontent.com/assets/17737516/18074075/9b57b3e8-6e9c-11e6-9fd0-dbed8d7c8f61.png)

作为模糊匹配的搜索条件

**Comment by richardzhai01** [comment]
看到了，有这个NCM no，移动到前面的位置

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18074670/d2758982-6ea0-11e6-8da4-dd75eea4e077.png)
