### ISSUE TITLE
Suspend的时候，不断的可以suspend

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#28]
![image](https://cloud.githubusercontent.com/assets/17737516/18077788/69cf6834-6eba-11e6-9f24-509a80351712.png)

**Comment by chulingchen** [comment]
该问题是有由于suspend之后没有刷新列表导致的，已修改

**Comment by richardzhai01** [comment]
我试了下，还是不会刷新啊，还没有部署上去，是吗？
