### ISSUE TITLE
suspend之后，打开记录update，还是可以点击按钮

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#29]
![image](https://cloud.githubusercontent.com/assets/17737516/18077896/154b90fc-6ebb-11e6-8ae5-cd5e29716f76.png)

![image](https://cloud.githubusercontent.com/assets/17737516/18077899/1f7399e4-6ebb-11e6-89b1-fc3eee0717b0.png)

**Comment by chulingchen** [comment]
这个地方是因为js报错了才导致按钮都可以操作，正常的情况下是这样的
![image](https://cloud.githubusercontent.com/assets/17737744/18081663/dbee3b44-6ecd-11e6-9463-93812f50b79b.png)

**Comment by richardzhai01** [comment]
那你的意思是现在已经部署到你们的开发机那里，还是说怎样

**Comment by Ge-Fei** [comment]
今天下班后的时候，会重新部署一个版本上去，修复今天提的那些问题~~
