### ISSUE TITLE
CSP Home的页面字段的调整，调整成一个页面全部显示，不要有左右拖动条

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#32]
![image](https://cloud.githubusercontent.com/assets/17737516/18114249/44583abe-6f68-11e6-86a6-8312d3d3c3a3.png)

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18115207/0102c704-6f70-11e6-92b3-93ad0dddd7e8.png)

**Comment by richardzhai01** [comment]
ok, 很好的
