### ISSUE TITLE
当前处理的email要高亮

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#33]
![image](https://cloud.githubusercontent.com/assets/17737516/18114370/3140c616-6f69-11e6-909c-e18c1f0a6631.png)

**Comment by chulingchen** [comment]
高亮的效果如下，另ALL WO列表的是否需要高亮显示
![image](https://cloud.githubusercontent.com/assets/17737744/18115076/e6ca11ea-6f6e-11e6-8e0b-dbbc7c291ce2.png)

**Comment by richardzhai01** [comment]
是的，可以啦，这个issue我close
