### ISSUE TITLE
页面名字的改变 logfile --》 attachment，加上一个向上的箭头

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#36]
![image](https://cloud.githubusercontent.com/assets/17737516/18114972/1435cb52-6f6e-11e6-8461-38d103710fe1.png)

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18115605/34ec63a6-6f73-11e6-8594-62852196406a.png)
