### ISSUE TITLE
在每个工单的页面点击suspend的时候，也要弹出对话框，输入suspend的原因，也要刷新列表的数据

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#37]
![image](https://cloud.githubusercontent.com/assets/17737516/18115016/799c3e5e-6f6e-11e6-9f5e-62a683af5b55.png)

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18118386/fc0f06f6-6f86-11e6-9534-fdb575f99cc4.png)
