### ISSUE TITLE
reassign和tryagain的时候，有提示，是返回到那个email的地址

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#39]
![image](https://cloud.githubusercontent.com/assets/17737516/18115190/e90e5460-6f6f-11e6-843a-91f27d179332.png)

**Comment by richardzhai01** [comment]
如果有不明白的，可以电话沟通

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18119195/0b9e714c-6f8c-11e6-80fd-b980762a08db.png)
![image](https://cloud.githubusercontent.com/assets/17737744/18119200/119d6328-6f8c-11e6-8c40-3af3b71bc6e7.png)

**Comment by richardzhai01** [comment]
yes, that is ok
