### ISSUE TITLE
Forwards to的时候有error

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#42]
![image](https://cloud.githubusercontent.com/assets/17737516/18121027/1f6264d2-6f95-11e6-8043-59ece37fd518.png)

**Comment by chulingchen** [comment]
这个状态下的工单有涉及到与APP的交互，这个错误是因为没有权限操作app的数据库引起的

**Comment by richardzhai01** [comment]
哦，明白，这个要等我去开放权限才可以，先留着这个问题，我明天去开权限
