### ISSUE TITLE
点击edit，然后直接save，会导致其他不能改的字段都可以编辑

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#43]
1. 状态时task confirm的记录：
   ![image](https://cloud.githubusercontent.com/assets/17737516/18121967/bb9cf958-6f99-11e6-8f74-a2d2def07115.png)
2. 点击save按钮，状态啊，slogan等的数据都可以改
   ![image](https://cloud.githubusercontent.com/assets/17737516/18122000/e989945c-6f99-11e6-8303-2c1815088496.png)

**Comment by chulingchen** [comment]
已修改
