### ISSUE TITLE
在all WO的查看中，还有approve的按钮存在

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#44]
![image](https://cloud.githubusercontent.com/assets/17737516/18122365/94d1c428-6f9b-11e6-8d93-0f39d9630f2d.png)

![image](https://cloud.githubusercontent.com/assets/17737516/18122374/aa4bd668-6f9b-11e6-91ff-45b6160a99a6.png)

**Comment by chulingchen** [comment]
已解决
![image](https://cloud.githubusercontent.com/assets/17737744/18123802/2451379a-6fa2-11e6-8a85-690f464e511a.png)

**Comment by richardzhai01** [comment]
OK
