### ISSUE TITLE
创建WO的时候，NE Type，System Version，NE type是必填的

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#47]
![image](https://cloud.githubusercontent.com/assets/17737516/18198688/affd3058-712f-11e6-87a2-679bcbe73c71.png)

![image](https://cloud.githubusercontent.com/assets/17737516/18198927/b5b09c78-7130-11e6-85e5-992e15e3d4ce.png)

**Comment by richardzhai01** [comment]
![image](https://cloud.githubusercontent.com/assets/17737516/18198941/d16ea928-7130-11e6-9c12-58f002c1baeb.png)

OPI的那里应该是一个表格

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18235664/42261dec-7350-11e6-8fbe-0c281eec80e6.png)
