### ISSUE TITLE
OPI的搜索需要带值进去，进行搜索

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#49]
![image](https://cloud.githubusercontent.com/assets/17737516/18201215/6b4c29d0-713b-11e6-9e91-ed3a2ff02601.png)

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18235200/4fa9a0d4-734a-11e6-85ab-ee75716523c6.png)
