### ISSUE TITLE
New OPI的时候，填写信息save，没有关闭当前的页面

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#50]
![image](https://cloud.githubusercontent.com/assets/17737516/18228446/f6f53e4a-7280-11e6-9917-ed8486bc513e.png)

**Comment by chulingchen** [comment]
已处理
![image](https://cloud.githubusercontent.com/assets/17737744/18235580/5798bb5e-734f-11e6-9b41-6c3d0d85efdd.png)
