### ISSUE TITLE
OPI select时，new OPI的时候，上面的table的NE type和下面的值不一致

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#51]
在New完一个OPI的时候
![image](https://cloud.githubusercontent.com/assets/17737516/18228453/46a40962-7281-11e6-8113-8ad23a2b3533.png)

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18235542/ceb451a4-734e-11e6-8a27-687d8cacde58.png)
