### ISSUE TITLE
New OPI的时候，需要传值进去，搜索条件有什么值，就传什么值

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#53]
![image](https://cloud.githubusercontent.com/assets/17737516/18228500/a07487bc-7283-11e6-948e-d75d6ba423dc.png)

通过handle list的页面进去：
![image](https://cloud.githubusercontent.com/assets/17737516/18228510/18435c14-7284-11e6-86ce-9bdfe62a3ccd.png)

然后点击opi select
![image](https://cloud.githubusercontent.com/assets/17737516/18228513/3df0ba4c-7284-11e6-90f0-d5d985502fda.png)

然后点击new opi，里面都没有值
![image](https://cloud.githubusercontent.com/assets/17737516/18228518/57519092-7284-11e6-9709-642013e79b37.png)

**Comment by linkcmkaizhang** [comment]
已解决
