### ISSUE TITLE
去除random code的邮件，在邮件里面都贴上ncm的外网的登录地址信息

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#54]
![image](https://cloud.githubusercontent.com/assets/17737516/18228549/3426bbfe-7286-11e6-9eaa-fe79d6ff0278.png)

![image](https://cloud.githubusercontent.com/assets/17737516/18228553/5ca149e6-7286-11e6-9707-e63ca1fdcf69.png)

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18265347/e0a871e8-7447-11e6-80c8-6d07b04afb4f.png)
