### ISSUE TITLE
当在一个WO里面new多个OPI，但是只选择其中一个的时候，点击get OPI，却把所有的OPI都load出来了

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#55]
![image](https://cloud.githubusercontent.com/assets/17737516/18228583/b8dd922c-7287-11e6-8126-0923779835f2.png)

![image](https://cloud.githubusercontent.com/assets/17737516/18228589/edd0512c-7287-11e6-90ac-1c2a8a411abf.png)

**Comment by chulingchen** [comment]
已解决
