### ISSUE TITLE
Forwards to的时候，domain是可下拉选择，下拉domain的值就是这个用户所在的所有的组的domain

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#60]
![image](https://cloud.githubusercontent.com/assets/17737516/18239000/b61fa564-7374-11e6-9436-dadc4ed8d458.png)

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18243988/51d42a5a-7390-11e6-87e0-c91b3a4ae893.png)
