### ISSUE TITLE
邮件的内容需要修改

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#61]
![image](https://cloud.githubusercontent.com/assets/17737516/18241480/f2ae70c8-7383-11e6-89c3-776d617fef24.png)

这封邮件是不需要发出来的
![image](https://cloud.githubusercontent.com/assets/17737516/18241667/0528a394-7385-11e6-84fa-dd0e6cdee4f6.png)

**Comment by chulingchen** [comment]
已解决

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18265310/b2defe30-7447-11e6-8cea-4449718ae6c9.png)
