### ISSUE TITLE
Approve页面上reassign，cancel等按钮，也要有提示框和刷新纪录

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#62]
![image](https://cloud.githubusercontent.com/assets/17737516/18261010/d38497ca-7425-11e6-8cae-f5e55d978998.png)

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18263911/a04c8524-743f-11e6-984b-fcf436a593b2.png)
![image](https://cloud.githubusercontent.com/assets/17737744/18263919/a87e0132-743f-11e6-85bb-d033d56406f1.png)
![image](https://cloud.githubusercontent.com/assets/17737744/18263930/b3063796-743f-11e6-8e6c-6cd8bfb2c3cd.png)
![image](https://cloud.githubusercontent.com/assets/17737744/18263948/d90111a0-743f-11e6-9c8a-583e7bf27adc.png)

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18264838/234c1a52-7445-11e6-8c98-197a6b754cc3.png)
![image](https://cloud.githubusercontent.com/assets/17737744/18264843/2d91b170-7445-11e6-998b-9620815d683a.png)
