### ISSUE TITLE
approve的页面上，logfile要改名字，同时logfile的按钮不工作

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#64]
![image](https://cloud.githubusercontent.com/assets/17737516/18261143/2234c178-7427-11e6-815b-aad8c42f8299.png)

改成下面的按钮
![image](https://cloud.githubusercontent.com/assets/17737516/18261151/2f5d5932-7427-11e6-80bb-afe37baa011f.png)

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18266019/2340d592-744b-11e6-8f3e-232693e0d58a.png)
