### ISSUE TITLE
在offline的有个字段是reason，但是在web的页面上没有了，请加上

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#65]
![image](https://cloud.githubusercontent.com/assets/17737516/18261343/67dbc328-7429-11e6-89b7-6b5e863d9e7a.png)

在web的页面上加上，是用来纪录rreassign，tryagain和suspend的原因的
![image](https://cloud.githubusercontent.com/assets/17737516/18261349/9424cba0-7429-11e6-978a-ffcd10a628e1.png)

在Reason那里，显示的格式如下，当点击suspend，在reason里面填写
Suspend： xxxxxxxx
如果是tryagain的，显示
Tryagain： xxxxxx

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18264982/e9a3c1a0-7445-11e6-8c20-b47aa326ade1.png)
