### ISSUE TITLE
搜索条件，搜索不出来结果

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#69]
搜索下面的记录：
![image](https://cloud.githubusercontent.com/assets/17737516/18263060/8b76069e-7439-11e6-9806-819e2b88201c.png)

输入44，点击query
![image](https://cloud.githubusercontent.com/assets/17737516/18263069/9c755d46-7439-11e6-8e3f-0271baa1cb04.png)

![image](https://cloud.githubusercontent.com/assets/17737516/18263076/a776bc8a-7439-11e6-90ff-75229ae75871.png)

**Comment by richardzhai01** [comment]
其他条件也要测试一下

**Comment by linkcmkaizhang** [comment]
slogan和ne做了加密  所以在这里不支持模糊查询，只能输入完全匹配的字符串，不然查不到

**Comment by richardzhai01** [comment]
先去除掉slogan和ne的搜索的
看看mop start time和end time是否查询的是否在区域之内的

**Comment by linkcmkaizhang** [comment]
已隐藏slogan和ne这2个查询条件。测试并解决存在的问题
