### ISSUE TITLE
MOP Level为A的时候，approve之后，状态变成approve by head，正确的是approval 

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#72]
MOP Level 是A
![image](https://cloud.githubusercontent.com/assets/17737516/18264585/b6d67350-7443-11e6-81ee-6303fe4b3c99.png)

Status是approval by head
![image](https://cloud.githubusercontent.com/assets/17737516/18264614/e317a772-7443-11e6-88e0-5b056777b58e.png)

这个状态时approval的状态

**Comment by chulingchen** [comment]
已解决
