### ISSUE TITLE
approve之后，上传result log，在approve的list里面的sender和send time需要填写值

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#73]
![image](https://cloud.githubusercontent.com/assets/17737516/18264947/b7325d76-7445-11e6-8815-53d982023b72.png)

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18267713/02f5b638-7453-11e6-9b1b-357e4ffbde57.png)
