### ISSUE TITLE
创建新的WO之后发送之后，关闭当前的页面

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#83]
![image](https://cloud.githubusercontent.com/assets/17737516/18269039/0304d2a2-7459-11e6-93cc-143d0cc112a1.png)

**Comment by chulingchen** [comment]
已解决

**Comment by richardzhai01** [comment]
这个问题还没有解决，还是没有关闭
![image](https://cloud.githubusercontent.com/assets/17737516/18344579/744240fc-75ea-11e6-9566-cb72cd968355.png)

**Comment by chulingchen** [comment]
已解决
