### ISSUE TITLE
内网的user的创建的页面有问题，save的位置

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#88]
![image](https://cloud.githubusercontent.com/assets/17737516/18341284/df32ede4-75db-11e6-8f99-dd6c96f53753.png)

![image](https://cloud.githubusercontent.com/assets/17737516/18341314/ff178052-75db-11e6-9fab-0fb3595ef03b.png)

**Comment by Ge-Fei** [comment]
已解决
