### ISSUE TITLE
logfile的按钮改成attachment

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#89]
![image](https://cloud.githubusercontent.com/assets/17737516/18344759/1cae9a4c-75eb-11e6-9648-08b200883812.png)

![image](https://cloud.githubusercontent.com/assets/17737516/18344783/3c88b55a-75eb-11e6-9bd0-7469e8b01020.png)

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18347872/b1838c72-75fa-11e6-8d56-47b529d54d3f.png)
