### ISSUE TITLE
邮件的url都要换成外网的地址

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#90]
![image](https://cloud.githubusercontent.com/assets/17737516/18345044/447bd9c6-75ec-11e6-88ad-f36b08363e60.png)

**Comment by chulingchen** [comment]
![image](https://cloud.githubusercontent.com/assets/17737744/18373598/0d6fe7ba-7678-11e6-9ce1-5ec8190ebcfa.png)
