### ISSUE TITLE
数据显示有些问题，ncm no都没有显示

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#91]
![image](https://cloud.githubusercontent.com/assets/17737516/18373641/6ee8e73a-7678-11e6-90f7-dbabbe31070e.png)

**Comment by linkcmkaizhang** [comment]
昨天测试工单乱码的时候产生了许多垃圾数据，在我们删除垃圾工单数据的时候没有删掉handleList的数据导致工单号匹配不上，所以建议工单号为空的handleList为空的删除掉是否可行？

**Comment by linkcmkaizhang** [comment]
哪些显示问号的  就是昨天产生的垃圾数据

**Comment by Ge-Fei** [comment]
建议将handler list 工单号为空的数据删掉。

**Comment by richardzhai01** [comment]
删了吧

**Comment by linkcmkaizhang** [comment]
删掉了
