### ISSUE TITLE
内网的工单也要高亮，当前的状态的处理人，得高亮

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#94]
![image](https://cloud.githubusercontent.com/assets/17737516/18432235/7f5aa2a0-7913-11e6-9cb0-01cc99882687.png)

**Comment by Ge-Fei** [comment]
已加
![image](https://cloud.githubusercontent.com/assets/15045906/18468113/0dfb358a-79d5-11e6-97de-33d4c458075a.png)
