### ISSUE TITLE
在All WO查看的工单，是没有Get OPI的按钮的

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#96]
![image](https://cloud.githubusercontent.com/assets/17737516/18432558/49347154-7915-11e6-9c1a-ea7b79af9e27.png)

![image](https://cloud.githubusercontent.com/assets/17737516/18432591/62e72312-7915-11e6-91ee-4fe770466a8c.png)

**Comment by Ge-Fei** [comment]
已处理
![image](https://cloud.githubusercontent.com/assets/15045906/18469396/a92b004e-79da-11e6-8aeb-ac3e56f75808.png)
