### ISSUE TITLE
减少到ftp的访问量，在打开附件上传，result log上传的时候，先不要连接ftp的

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#98]
可以加一个load的按钮，当用户点击load的时候，才去load ftp的内容，这样可以减少ftp连接的次数，也增加用户体验，因为每次开，都要等很久
![image](https://cloud.githubusercontent.com/assets/17737516/18460977/8c8ec916-79a8-11e6-9aad-27171d3d5a8e.png)

其他所有的上传的功能都这样做

**Comment by Ge-Fei** [comment]
Result log, attachment, opi upload 已加：
![image](https://cloud.githubusercontent.com/assets/15045906/18471848/5b5800ea-79e6-11e6-8580-f0c9a34629f1.png)
