### ISSUE TITLE
在外网中，点击OPI不能看到详细的信息

### ISSUE THREAD

**Issue by richardzhai01** [csdperic/csdp#99]
![image](https://cloud.githubusercontent.com/assets/17737516/18462767/d026287c-79b7-11e6-8302-b635c0941142.png)

**Comment by Ge-Fei** [comment]
内网已改~
![image](https://cloud.githubusercontent.com/assets/15045906/18472292/14ff7b02-79e9-11e6-86df-e5bdda0a02b7.png)

**Comment by Ge-Fei** [comment]
说错，外网已改
